Task3 Create WeatherСonsoleApp
alesyalis/ALESIA_LIS_INDIVIDUAL_MENTORSHIP pull request #1
Opened 2022-01-25 07:01 UTC by alesyalis

2022-01-25 07:24 UTC, Xodoc approved these changes

2022-01-25 14:51 UTC, ihhyy approved these changes

2022-01-25 16:15 UTC, denja2 requested changes

2022-01-25 16:15 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Services/Abstract/IWeatherServices.cs
> +    public interface IWeatherServices
IWeatherService

2022-01-25 16:15 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Services/Abstract/IWeatherServices.cs
> +        void GetWeather(string cityName);
Make all methods async please

2022-01-25 16:15 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Services/WeatherServices.cs
> +                string url = string.Format("http://api.openweathermap.org/data/2.5/weather?q={0}&units=metric&appid=8e943ed8b016561c73b8a1920366ef79", cityName);
Use var

2022-01-25 16:15 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Services/WeatherServices.cs
> +                string url = string.Format("http://api.openweathermap.org/data/2.5/weather?q={0}&units=metric&appid=8e943ed8b016561c73b8a1920366ef79", cityName);
Move url and secret to the config file

2022-01-25 16:15 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Services/WeatherServices.cs
> +                Console.WriteLine("В {0}: {1} °C {2} ", weatherResponse.Name, weatherResponse.Main.Temp,
The above logic is DAL, below is  BL

2022-01-25 16:15 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Validators/WeatherValidator.cs
> +        public static bool IsValidCityName(string cityName)
Why static

2022-01-25 16:15 UTC, denja2 commented on Weather.СonsoleApp/Weather.СonsoleApp/Program.cs
> +                if (WeatherValidator.IsValidCityName(city))
this is BL logic

2022-01-28 09:13 UTC, denja2 requested changes

2022-01-28 09:13 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Services/WeatherService.cs
> +        private readonly IValidator _validator;
Empty line

2022-01-28 09:13 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Services/WeatherService.cs
> +        private WeatherResponseDTO MapWeather(WeatherResponse weatherResponse)
MapTo

2022-01-28 09:13 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Services/WeatherService.cs
> +            var weatherDTO = new WeatherResponseDTO
Check for null

2022-01-28 09:13 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Services/WeatherService.cs
> +                return "Nothing";
?

2022-01-28 09:13 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Validators/Abstract/Validator.cs
> +            if (name == string.Empty)
IsNullOrWhiteSpace

2022-01-28 09:13 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Validators/Abstract/Validator.cs
> +                throw new ArgumentNullException("Entering the city is required\n");
Create your custom ValidationException

2022-01-28 09:13 UTC, denja2 commented on Weather.СonsoleApp/Weather.DataAccess/Repositories/WeatherRepository.cs
> +            var responce = await _httpClient.GetStringAsync($"{api}={cityName}&units=metric&appid={key}");
Move the string to the config

2022-01-28 09:13 UTC, denja2 commented on Weather.СonsoleApp/Weather.СonsoleApp/Program.cs
> +            _configuration.Api = ConfigurationManager.AppSettings["api"];
Move to container initialization

2022-01-29 18:24 UTC, merged