add WeatherServiceTest
alesyalis/ALESIA_LIS_INDIVIDUAL_MENTORSHIP pull request #2
Opened 2022-01-31 07:37 UTC by alesyalis

2022-02-02 07:10 UTC, Xodoc approved these changes

2022-02-02 07:15 UTC, ihhyy approved these changes

2022-02-02 08:04 UTC, denja2 requested changes

2022-02-02 08:04 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Service/WeatherServiceTest.cs
> +        public async Task GetWeatherAsync_Sucess()
Read about teat naming approaches

2022-02-02 08:04 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Service/WeatherServiceTest.cs
> +            var weater = new WeatherResponse()
AAA //Arrange //Act //Assert

2022-02-02 08:04 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Class1.cs
> +    public class Class1
?

2022-02-02 08:04 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Service/ValidatorTest.cs
> +        [Test]
?

2022-02-02 08:04 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Service/ValidatorTest.cs
> +            Assert.Throws<ValidationException>(() => _validator.ValidateCityByName(name));
Check error text

2022-02-02 08:04 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Service/ValidatorTest.cs
> +        public void ValidateCityByName_IfStringEmpty_ValidationIsFaild(string name)
Check the name

2022-02-02 08:04 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Service/ValidatorTest.cs
> +            Assert.Throws<ValidationException>(() => _validator.ValidateCityByName(name));
Add success path

2022-02-02 08:04 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Service/WeatherServiceTest.cs
> +            _weatherRepositoryMock.Setup(x => x.GetWeatherAsync(name)).ReturnsAsync(weater);
arrange

2022-02-02 19:03 UTC, alesyalis commented on Weather.СonsoleApp/Weather.Tests/Service/WeatherServiceTest.cs
> +        public async Task GetWeatherAsync_Sucess()
done

2022-02-02 19:03 UTC, alesyalis commented on Weather.СonsoleApp/Weather.Tests/Service/WeatherServiceTest.cs
> +            var weater = new WeatherResponse()
done

2022-02-02 19:03 UTC, alesyalis commented on Weather.СonsoleApp/Weather.Tests/Class1.cs
> +    public class Class1
done

2022-02-02 19:03 UTC, alesyalis commented on Weather.СonsoleApp/Weather.Tests/Service/ValidatorTest.cs
> +        [Test]
done

2022-02-02 19:03 UTC, alesyalis commented on Weather.СonsoleApp/Weather.Tests/Service/ValidatorTest.cs
> +            Assert.Throws<ValidationException>(() => _validator.ValidateCityByName(name));
done

2022-02-02 19:04 UTC, alesyalis commented on Weather.СonsoleApp/Weather.Tests/Service/ValidatorTest.cs
> +        public void ValidateCityByName_IfStringEmpty_ValidationIsFaild(string name)
done

2022-02-02 19:05 UTC, alesyalis commented on Weather.СonsoleApp/Weather.Tests/Service/WeatherServiceTest.cs
> +            _weatherRepositoryMock.Setup(x => x.GetWeatherAsync(name)).ReturnsAsync(weater);
done

2022-02-03 11:06 UTC, alesyalis commented on Weather.СonsoleApp/Weather.Tests/Service/ValidatorTest.cs
> +            Assert.Throws<ValidationException>(() => _validator.ValidateCityByName(name));
done

2022-02-03 16:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/DTOs/WeatherResponseNew.cs
> +    public class WeatherResponseNew
Remove new

2022-02-03 16:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Services/Abstract/IWeatherService.cs
> +        // Task<string> GetWeatherAsync(string cityName);
remove

2022-02-03 16:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Service/ValidatorTest.cs
> +            Assert.Throws<ValidationException>(() => _validator.ValidateCityByName(name));
??

2022-02-03 16:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Service/ValidatorTest.cs
> +        }
remove

2022-02-03 16:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Service/ValidatorTest.cs
> +        [Test]
TestCase null and empty

2022-02-03 16:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Service/ValidatorTest.cs
> +    }
add success pass

2022-02-03 16:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Service/WeatherServiceTest.cs
> +        [Test]
Use testcase

2022-02-03 16:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Service/WeatherServiceTest.cs
> +            _validatorMock.Verify(x => x.ValidateCityByName(name), Times.Never());
Move to Assert

2022-02-03 16:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Service/WeatherServiceTest.cs
> +            Assert.AreEqual(message, result.Message);
is error

2022-02-03 16:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Service/WeatherServiceTest.cs
> +            Assert.IsFalse(result.IsError);
If exception is thrown from repo and validator

2022-02-03 16:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.СonsoleApp/Program.cs
>                  {
Unhandled error

2022-02-03 16:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Service/WeatherServiceTest.cs
> +        [TestCase("")]
Test

2022-02-03 16:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.Tests/Service/WeatherServiceTest.cs
> +        }
Case with exception from validator

2022-02-03 16:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.IntegrationTest/IntegrationTest.cs
> +namespace Weather.IntegrationTest
Remove integration tests from pr

2022-02-04 06:27 UTC, denja2 approved these changes

2022-02-04 07:32 UTC, merged