add IntegrationTest
alesyalis/ALESIA_LIS_INDIVIDUAL_MENTORSHIP pull request #4
Opened 2022-02-07 09:59 UTC by alesyalis

2022-02-07 10:03 UTC, ihhyy approved these changes

2022-02-07 13:47 UTC, Xodoc approved these changes

2022-02-07 13:47 UTC, Xodoc commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +        private IWeatherRepository _weatherRepository;
make fields readonly

2022-02-07 13:47 UTC, Xodoc commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            await _weatherRepository.GetWeatherAsync(name);
Remove

2022-02-07 16:38 UTC, denja2 requested changes

2022-02-07 16:38 UTC, denja2 commented on Weather.СonsoleApp/Weather.IntegrationTest/IConfigTest.cs
> +    }
Why class ia named from I?

2022-02-07 16:38 UTC, denja2 commented on Weather.СonsoleApp/Weather.IntegrationTest/IConfigTest.cs
> +        public string Url =>  "https://api.openweathermap.org/data/2.5/weather?q";
Move to config

2022-02-07 16:38 UTC, denja2 commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +        private IWeatherRepository _weatherRepository;
+

2022-02-07 16:38 UTC, denja2 commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            _validator.ValidateCityByName(name);
not needed

2022-02-07 16:38 UTC, denja2 commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            Assert.Equal(message, messageResult);
Use regex

2022-02-07 16:38 UTC, denja2 commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            Assert.True(response.IsError);
what is the message?

2022-02-07 19:34 UTC, alesyalis commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            Assert.True(response.IsError);
add

2022-02-07 19:35 UTC, alesyalis commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            _validator.ValidateCityByName(name);
done

2022-02-07 19:35 UTC, alesyalis commented on Weather.СonsoleApp/Weather.IntegrationTest/IConfigTest.cs
> +    }
done

2022-02-07 19:35 UTC, alesyalis commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +        private IWeatherRepository _weatherRepository;
done

2022-02-07 19:47 UTC, alesyalis commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            Assert.Equal(message, messageResult);
done

2022-02-08 07:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +        private readonly ConfigTest _configuratio;
name

2022-02-08 07:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            var model = await _weatherRepository.GetWeatherAsync(name);
?

2022-02-08 07:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            _validator.ValidateCityByName(name);
remove

2022-02-08 07:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            void actualResult() => _validator.ValidateCityByName(name);
?

2022-02-08 07:48 UTC, denja2 commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            //Act
call service in act

2022-02-08 11:12 UTC, alesyalis commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            await _weatherRepository.GetWeatherAsync(name);
done

2022-02-08 11:13 UTC, alesyalis commented on Weather.СonsoleApp/Weather.IntegrationTest/IConfigTest.cs
> +        public string Url =>  "https://api.openweathermap.org/data/2.5/weather?q";
done

2022-02-08 11:13 UTC, alesyalis commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +        private readonly ConfigTest _configuratio;
done

2022-02-08 11:13 UTC, alesyalis commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            var model = await _weatherRepository.GetWeatherAsync(name);
done

2022-02-08 11:13 UTC, alesyalis commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            _validator.ValidateCityByName(name);
done

2022-02-08 11:14 UTC, alesyalis commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            void actualResult() => _validator.ValidateCityByName(name);
done

2022-02-09 07:38 UTC, denja2 commented on Weather.СonsoleApp/Weather.IntegrationTest/ConfigTest.cs
> +            ApiKey = config["AppString:0:ApiKey"];
Refactor this

2022-02-09 07:38 UTC, denja2 commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            var description2 = "It's fresh.";
Regex in arrange

2022-02-09 10:51 UTC, alesyalis commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            var description2 = "It's fresh.";
done

2022-02-09 10:53 UTC, alesyalis commented on Weather.СonsoleApp/Weather.IntegrationTest/ConfigTest.cs
> +            ApiKey = config["AppString:0:ApiKey"];
done

2022-02-09 11:02 UTC, merged