Task6
alesyalis/ALESIA_LIS_INDIVIDUAL_MENTORSHIP pull request #5
Opened 2022-02-10 08:53 UTC by alesyalis

2022-02-10 09:29 UTC, denja2 requested changes

2022-02-10 09:29 UTC, denja2 commented on ClassLibrary1/ClassLibrary1/Class1.cs
> +    public class Class1
???

2022-02-10 09:29 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/DTOs/ForecastResponseMessage.cs
> +    public class ForecastResponseMessage
Don't create duplicate

2022-02-10 09:29 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Services/WeatherService.cs
> +        public async Task<List<ForecastResponseMessage>> GetForecastAsync(string cityName, int days)
Add input class

2022-02-10 09:29 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Services/WeatherService.cs
> +            _validator.ValidateCityByName(cityName);
ValidateForecastRequest

2022-02-10 09:29 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Services/WeatherService.cs
> +        public async Task<List<ForecastResponseMessage>> GetForecastAsync(string cityName, int days)
return WeatherResponseMessage

2022-02-10 09:29 UTC, denja2 commented on Weather.СonsoleApp/Weather.DataAccess/Models/ForecastDescription.cs
> +        public double Temp_min { get; set; }
Use attributes

2022-02-10 09:29 UTC, denja2 commented on Weather.СonsoleApp/Weather.DataAccess/Repositories/WeatherRepository.cs
> +            var location = await GetLocationAsync(cityName);
locations

2022-02-10 09:29 UTC, denja2 commented on Weather.СonsoleApp/Weather.DataAccess/Repositories/WeatherRepository.cs
> +            var lat = location?.FirstOrDefault()?.Lat;
Get first location? then validate for null

2022-02-10 09:29 UTC, denja2 commented on Weather.СonsoleApp/Weather.DataAccess/Repositories/WeatherRepository.cs
> +            var responce = await _httpClient.GetAsync($"{urlBase}{urlForecast}lat={lat}&lon={lon}&cnt={days}&units=metric&appid={key}");
response

2022-02-12 19:26 UTC, Xodoc commented on Weather.СonsoleApp/Weather.BL/Validators/Abstract/Validator.cs
> +            if (days == 0)
Why is it only checked for 0 ? U need to consider the option with a negative value

2022-02-12 19:26 UTC, Xodoc commented on Weather.СonsoleApp/Weather.IntegrationTest/appsettings.json
> +  "Url": "https://api.openweathermap.org/data/2.5/weather?q",
Remove "weather?q", u have urlWeather

2022-02-12 19:26 UTC, Xodoc commented on Weather.СonsoleApp/Weather.СonsoleApp/Program.cs
> +            var listCommand = new List<ICommand>();
var listCommand = new List<ICommand>{ getWeather, getForecast };
I think it will be better 🙂

2022-02-14 10:23 UTC, Xodoc approved these changes

2022-02-14 14:13 UTC, ihhyy commented on Weather.СonsoleApp/Weather.BL/Services/WeatherService.cs
> +            var description = forecastDescription.Description;
Do you need description here ?

2022-02-14 14:13 UTC, ihhyy commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +
Spaces

2022-02-14 14:13 UTC, ihhyy commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +
Space

2022-02-14 14:25 UTC, ihhyy approved these changes

2022-02-14 15:39 UTC, denja2 requested changes

2022-02-14 15:39 UTC, denja2 commented on Weather.СonsoleApp/AppConfiguration/AppConfig/Config.cs
> +        public string UrlBase { get { return ConfigurationManager.AppSettings["urlBase"]; } }
I missed it previously, not the best way to initialize config

2022-02-14 15:39 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Services/WeatherService.cs
> +            forecastResponse.List.ForEach(x => responseMessage.Message += string.Join(",", $"{x.Date.DayOfWeek} In {forecastResponse.CityName.Name}" +
Create first part of message and then second created by join

2022-02-14 15:39 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Services/WeatherService.cs
> +            var description = forecastDescription.Description;
+

2022-02-14 15:39 UTC, denja2 commented on Weather.СonsoleApp/Weather.IntegrationTest/ConfigTest.cs
> +                return new ConfigurationBuilder().AddJsonFile("appsettings.json")
No need to read config file in each property

2022-02-14 15:39 UTC, denja2 commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +            // Assert
?

2022-02-14 15:39 UTC, denja2 commented on Weather.СonsoleApp/Weather.IntegrationTest/Service/WeatherServiceIntegrationTest.cs
> +        public async Task GetForecastsync_ReceivedIncorrectWeather_IsErrorTrue()
check the method name

2022-02-14 15:39 UTC, denja2 commented on Weather.СonsoleApp/Weather.BL/Validators/Abstract/Validator.cs
> +            if (days <= 0)
!!!! days from config

2022-02-16 10:28 UTC, merged